BEGIN;

DROP TRIGGER IF EXISTS set_api_clients_updated_at ON api_clients;
DROP TRIGGER IF EXISTS set_subscriptions_updated_at ON subscriptions;
DROP TRIGGER IF EXISTS set_organizations_updated_at ON organizations;
DROP TRIGGER IF EXISTS set_medical_passports_updated_at ON medical_passports;
DROP TRIGGER IF EXISTS set_user_medications_updated_at ON user_medications;
DROP TRIGGER IF EXISTS set_prescription_items_updated_at ON prescription_items;
DROP TRIGGER IF EXISTS set_prescriptions_updated_at ON prescriptions;
DROP TRIGGER IF EXISTS set_contraindications_updated_at ON contraindications;
DROP TRIGGER IF EXISTS set_drug_interactions_updated_at ON drug_interactions;
DROP TRIGGER IF EXISTS set_drug_equivalents_updated_at ON drug_equivalents;
DROP TRIGGER IF EXISTS set_drug_presentations_updated_at ON drug_presentations;
DROP TRIGGER IF EXISTS set_drug_products_updated_at ON drug_products;
DROP TRIGGER IF EXISTS set_active_ingredients_updated_at ON active_ingredients;
DROP TRIGGER IF EXISTS set_user_profiles_updated_at ON user_profiles;
DROP TRIGGER IF EXISTS set_users_updated_at ON users;

DROP INDEX IF EXISTS idx_audit_events_created_at;
DROP INDEX IF EXISTS idx_audit_events_actor;
DROP INDEX IF EXISTS idx_api_usage_logs_client_time;
DROP INDEX IF EXISTS idx_api_clients_org_id;
DROP INDEX IF EXISTS idx_medical_passports_status;
DROP INDEX IF EXISTS idx_medical_passports_user_id;
DROP INDEX IF EXISTS idx_medication_interaction_checks_user_id;
DROP INDEX IF EXISTS idx_user_medications_presentation_id;
DROP INDEX IF EXISTS idx_user_medications_status;
DROP INDEX IF EXISTS idx_user_medications_user_id;
DROP INDEX IF EXISTS idx_prescription_items_prescription_id;
DROP INDEX IF EXISTS idx_prescriptions_status;
DROP INDEX IF EXISTS idx_prescriptions_user_id;
DROP INDEX IF EXISTS idx_contraindications_ingredient;
DROP INDEX IF EXISTS idx_drug_equivalents_target;
DROP INDEX IF EXISTS idx_drug_equivalents_source;
DROP INDEX IF EXISTS idx_drug_synonyms_synonym_trgm;
DROP INDEX IF EXISTS idx_drug_presentation_ingredients_ingredient_id;
DROP INDEX IF EXISTS idx_drug_presentation_ingredients_presentation_id;
DROP INDEX IF EXISTS uq_drug_presentations_signature_ci;
DROP INDEX IF EXISTS idx_drug_presentations_product_id;
DROP INDEX IF EXISTS idx_drug_products_brand_name_trgm;
DROP INDEX IF EXISTS uq_drug_products_country_brand_manufacturer_ci;
DROP INDEX IF EXISTS idx_drug_products_country_code;
DROP INDEX IF EXISTS idx_active_ingredients_inn_name_trgm;
DROP INDEX IF EXISTS uq_active_ingredients_inn_name_ci;
DROP INDEX IF EXISTS idx_active_ingredients_atc_code;
DROP INDEX IF EXISTS idx_users_country_code;
DROP INDEX IF EXISTS idx_users_role;

DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS api_usage_logs;
DROP TABLE IF EXISTS api_clients;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS organization_members;
DROP TABLE IF EXISTS organizations;
DROP TABLE IF EXISTS medical_passport_snapshots;
DROP TABLE IF EXISTS medical_passports;
DROP TABLE IF EXISTS medication_interaction_check_items;
DROP TABLE IF EXISTS medication_interaction_checks;
DROP TABLE IF EXISTS user_medications;
DROP TABLE IF EXISTS prescription_items;
DROP TABLE IF EXISTS prescriptions;
DROP TABLE IF EXISTS contraindications;
DROP TABLE IF EXISTS drug_interactions;
DROP TABLE IF EXISTS drug_equivalents;
DROP TABLE IF EXISTS drug_synonyms;
DROP TABLE IF EXISTS drug_presentation_ingredients;
DROP TABLE IF EXISTS drug_presentations;
DROP TABLE IF EXISTS drug_products;
DROP TABLE IF EXISTS dosage_forms;
DROP TABLE IF EXISTS active_ingredients;
DROP TABLE IF EXISTS user_conditions;
DROP TABLE IF EXISTS clinical_conditions;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS supported_languages;
DROP TABLE IF EXISTS countries;

DROP FUNCTION IF EXISTS set_updated_at();

DROP TYPE IF EXISTS api_client_status;
DROP TYPE IF EXISTS subscription_status;
DROP TYPE IF EXISTS passport_status;
DROP TYPE IF EXISTS prescription_processing_status;
DROP TYPE IF EXISTS risk_level;
DROP TYPE IF EXISTS equivalence_type;
DROP TYPE IF EXISTS medication_status;
DROP TYPE IF EXISTS medication_source;
DROP TYPE IF EXISTS user_role;

COMMIT;
